spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    #enable_lazy_load_no_trans: true

file:
  working-dir: testUploads

---
spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration/common

  # ===============================
  # GREEN MAIL TEST SERVER
  # ===============================
  mail:
    host: localhost
    password: emailpass
    username: emailuser
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 3025
          auth: false
          starttls:
            enable: false
            required: false
---
retry-template-policy:
  simple:
    max-retry-attempts: 3
  fixed:
    fixed-backoff-duration: 1000

